apiVersion: apps/v1
kind: Deployment
metadata:
  name: xorb-api
spec:
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            cpu: "300m"
            memory: "768Mi"
          limits:
            cpu: "1"
            memory: "1.5Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xorb-worker
spec:
  template:
    spec:
      containers:
      - name: worker
        resources:
          requests:
            cpu: "750m"
            memory: "1.5Gi"
          limits:
            cpu: "2"
            memory: "3Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xorb-orchestrator
spec:
  template:
    spec:
      containers:
      - name: orchestrator
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"