repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=5120']  # 5MB limit
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.5'
    hooks:
      - id: bandit
        args: ['-r', 'src/', 'tools/', '--skip', 'B101,B601']
        exclude: ^tests/
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: detect-private-key
        name: Detect Private Key
        entry: python tools/hooks/detect_private_key.py
        language: python
        files: .*
      - id: project-fmt
        name: Project Format Check
        entry: bash -c 'if [ -f pyproject.toml ]; then python -m ruff format --check . || python -m black --check .; fi'
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff-lint
        name: Ruff/Flake8 Lint
        entry: bash -c 'python -m ruff check . || python -m flake8 .'
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff-security
        name: Ruff Security Check
        entry: bash -c 'python -m ruff check --select S . || true'
        language: system
        pass_filenames: false
        always_run: true
      - id: redis-pubsub-block
        name: Block Redis Pub/Sub (ADR-002)
        entry: tools/hooks/redis_pubsub_block.sh
        language: system
        pass_filenames: false
      - id: adr-locked-guard
        name: ADR Locked Sections Guard
        entry: python tools/hooks/adr_locked_guard.py
        language: python
        pass_filenames: false
      - id: security-scan-quick
        name: Quick Security Scan
        entry: python tools/security/security_scan.py --format text
        language: python
        pass_filenames: false
        always_run: true