repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        args: ['--max-size=10485760'] # 10MB
      - id: git-check
        args: ['--assume-unchanged', '--no-merge-conflict']
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        args: ['--verbose', '--redact']
  - repo: local
    hooks:
      - id: forbid-redis-bus
        name: ADR-002 forbid Redis as bus
        entry: bash -lc 'git diff --cached --name-only | xargs -r grep -nE "\b(redis\.(pubsub|subscribe|psubscribe)|redis\.client\.PubSub)\b" && echo "❌ Redis bus usage detected" && exit 1 || exit 0'
        language: system
        pass_filenames: false
      - id: jwt-no-hs256
        name: Forbid HS256 JWT usage (security vulnerability)
        entry: bash -lc 'git diff --cached --name-only | xargs -r grep -nE "\bHS256\b" && echo "❌ HS256 JWT usage detected - use RS256 or ES256" && exit 1 || exit 0'
        language: system
        pass_filenames: false
      - id: tls13-required
        name: Enforce TLS 1.3 minimum version
        entry: bash -lc 'git diff --cached --name-only | xargs -r grep -nE "(ssl_protocols|tls_version|TLSv1\.[0-2])" && echo "❌ TLS < 1.3 detected - enforce TLS 1.3+" && exit 1 || exit 0'
        language: system
        pass_filenames: false
      - id: detect-large-files
        name: Detect large files (>10MB)
        entry: >
          bash -lc 'find . -type f -size +10M -not -path "./.git/*" -not -path "./venv/*" -not -path "./.venv/*" -exec echo "Large file detected: {}" \; | grep -q "Large file" && exit 1 || exit 0'
        language: system
        pass_filenames: false
