# YAMLLint configuration for XORB
extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning

  # Comments
  comments:
    min-spaces-from-content: 1

  # Document start
  document-start:
    present: false

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Key duplicates
  key-duplicates:
    level: error

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false

# Ignore specific files
ignore: |
  .github/workflows/
  node_modules/
  .venv/
  __pycache__/