
version: '3.8'
services:
  development:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=xorb
      - POSTGRES_PASSWORD=xorb
      - POSTGRES_DB=xorb
    ports:
      - "5432:5432"
  nats:
    image: nats:2.9-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
