# Default values for pgvector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgresql:
  image:
    registry: docker.io
    repository: pgvector/pgvector
    tag: pg15
  auth:
    postgresPassword: "your-password"
    username: "postgres"
    database: "xorb"
  persistence:
    enabled: true
    size: 10Gi
