# Blackbox Exporter Configuration for XORB
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200]
      preferred_ip_protocol: "ip4"
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: true

  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      method: POST
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200]
      headers:
        Content-Type: application/json

  http_basic_auth:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200]
      basic_auth:
        username: "monitor"
        password: "monitor"

  tcp_connect:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"

  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"

  dns_tcp:
    prober: dns
    timeout: 5s
    dns:
      preferred_ip_protocol: "ip4"
      transport_protocol: "tcp"
      query_name: "xorb.local"
      query_type: "A"

  dns_udp:
    prober: dns
    timeout: 5s
    dns:
      preferred_ip_protocol: "ip4"
      transport_protocol: "udp"
      query_name: "xorb.local"
      query_type: "A"
