[Definition]
failregex = ^.*\[ERROR\].*Client <HOST>.*authentication failed.*$
            ^.*\[WARNING\].*Client <HOST>.*rate limit exceeded.*$
            ^.*\[ERROR\].*Client <HOST>.*malicious request detected.*$
ignoreregex =
