version: '3.9'

# Observability stack for Xorb PTaaS platform
services:
  # Prometheus metrics collector
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: xorb_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules:/etc/prometheus/rules:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    networks:
      - xorb-network
    # EPYC optimization - 1 vCPU core, 2GB RAM
    cpu_quota: 100000
    cpuset: "15"
    mem_limit: 2g
    mem_reservation: 1g
    restart: unless-stopped

  # Grafana dashboard
  grafana:
    image: grafana/grafana:10.0.0
    container_name: xorb_grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=xorb_grafana_admin_2024
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - xorb-network
    # EPYC optimization - 0.5 vCPU core, 1GB RAM
    cpu_quota: 50000
    mem_limit: 1g
    restart: unless-stopped
    depends_on:
      - prometheus

networks:
  xorb-network:
    external: true

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local