# Alertmanager configuration for PTaaS platform
# Handles alert routing, grouping, and notification delivery

global:
  # SMTP configuration for email alerts
  smtp_smarthost: 'smtp.sendgrid.net:587'
  smtp_from: 'alerts@verteidiq.com'
  smtp_auth_username: 'apikey'
  smtp_auth_password_file: '/etc/alertmanager/smtp_password'
  smtp_require_tls: true

# Templates for custom alert formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Alert routing tree
route:
  # Root route configuration
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default-receiver'
  
  # Child routes for specific alert types
  routes:
    # Critical security alerts - immediate response
    - match:
        severity: critical
      group_by: ['alertname']
      group_wait: 0s
      group_interval: 1m
      repeat_interval: 30m
      receiver: 'security-critical'
      routes:
        # Tenant isolation violations - highest priority
        - match:
            security_event: tenant_isolation_breach
          receiver: 'security-emergency'
          group_wait: 0s
          repeat_interval: 5m
        
        # Data breach incidents
        - match:
            category: data_breach
          receiver: 'security-emergency'
          group_wait: 0s
          repeat_interval: 10m
        
        # Secrets exposure
        - match:
            security_event: secrets_exposure
          receiver: 'security-emergency'
          group_wait: 0s
          repeat_interval: 10m

    # High severity alerts - urgent response
    - match:
        severity: high
      group_wait: 2m
      group_interval: 5m
      repeat_interval: 2h
      receiver: 'high-priority'
      routes:
        # SOC2 compliance failures
        - match:
            compliance_impact: soc2
          receiver: 'compliance-team'
        
        # Infrastructure security issues
        - match:
            category: infrastructure_security
          receiver: 'devops-security'

    # SLO violations - business impact
    - match_re:
        alertname: '.*SLO.*'
      group_by: ['slo', 'burn_rate']
      group_wait: 5m
      group_interval: 10m
      repeat_interval: 6h
      receiver: 'sre-team'
      routes:
        # Fast burn SLO alerts - immediate attention
        - match:
            burn_rate: fast
          receiver: 'sre-urgent'
          group_wait: 1m
          repeat_interval: 2h

    # Warning alerts - standard monitoring
    - match:
        severity: warning
      group_wait: 10m
      group_interval: 15m
      repeat_interval: 12h
      receiver: 'ops-team'

    # Development and staging alerts
    - match:
        environment: 'staging'
      receiver: 'dev-team'
      group_interval: 30m
      repeat_interval: 24h
    
    - match:
        environment: 'development'
      receiver: 'dev-team'
      group_interval: 1h
      repeat_interval: 24h

# Inhibition rules to reduce alert noise
inhibit_rules:
  # Inhibit warning alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

  # Inhibit individual service alerts when cluster alerts are firing
  - source_match:
      alertname: 'ClusterDown'
    target_match_re:
      alertname: '.*Service.*'
    equal: ['cluster']

  # Inhibit slow burn when fast burn is active
  - source_match:
      burn_rate: 'fast'
    target_match:
      burn_rate: 'slow'
    equal: ['slo']

# Receiver configurations
receivers:
  # Default receiver for non-matching alerts
  - name: 'default-receiver'
    email_configs:
      - to: 'ops@verteidiq.com'
        subject: 'PTaaS Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}
            {{ .Name }}: {{ .Value }}{{ end }}
          {{ end }}

  # Critical security alerts - multi-channel notification
  - name: 'security-critical'
    email_configs:
      - to: 'security@verteidiq.com,ciso@verteidiq.com'
        subject: 'CRITICAL SECURITY ALERT: {{ .GroupLabels.alertname }}'
        headers:
          Priority: 'urgent'
        body: |
          {{ template "security_alert.html" . }}
    
    slack_configs:
      - api_url_file: '/etc/alertmanager/slack_webhook'
        channel: '#security-alerts'
        color: 'danger'
        title: 'CRITICAL SECURITY ALERT'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          {{ if .Annotations.immediate_action }}*Immediate Action Required:* {{ .Annotations.immediate_action }}{{ end }}
          {{ if .Annotations.runbook_url }}Runbook: {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}
    
    pagerduty_configs:
      - service_key_file: '/etc/alertmanager/pagerduty_key'
        severity: 'critical'
        description: '{{ .GroupLabels.alertname }}: {{ .CommonAnnotations.summary }}'
        details:
          environment: '{{ .CommonLabels.environment }}'
          cluster: '{{ .CommonLabels.cluster }}'
          runbook: '{{ .CommonAnnotations.runbook_url }}'

  # Emergency security response - immediate escalation
  - name: 'security-emergency'
    email_configs:
      - to: 'security@verteidiq.com,ciso@verteidiq.com,ceo@verteidiq.com'
        subject: 'SECURITY EMERGENCY: {{ .GroupLabels.alertname }}'
        headers:
          Priority: 'urgent'
          Importance: 'high'
        body: |
          SECURITY EMERGENCY DETECTED
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ if .Annotations.immediate_action }}
          IMMEDIATE ACTION REQUIRED: {{ .Annotations.immediate_action }}
          {{ end }}
          {{ if .Annotations.runbook_url }}
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}
          
          Time: {{ .StartsAt }}
          Labels: {{ range .Labels.SortedPairs }}
            {{ .Name }}: {{ .Value }}{{ end }}
          {{ end }}
    
    slack_configs:
      - api_url_file: '/etc/alertmanager/slack_webhook'
        channel: '#security-emergency'
        color: 'danger'
        title: '🚨 SECURITY EMERGENCY 🚨'
        text: |
          @channel IMMEDIATE ATTENTION REQUIRED
          
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          
          {{ if .Annotations.immediate_action }}
          🔥 *IMMEDIATE ACTION:* {{ .Annotations.immediate_action }}
          {{ end }}
          
          📖 Runbook: {{ .Annotations.runbook_url }}
          {{ end }}
    
    pagerduty_configs:
      - service_key_file: '/etc/alertmanager/pagerduty_emergency_key'
        severity: 'critical'
        description: 'SECURITY EMERGENCY: {{ .CommonAnnotations.summary }}'
        
    # SMS notifications for critical security events
    webhook_configs:
      - url: 'https://api.verteidiq.com/alerts/sms'
        http_config:
          bearer_token_file: '/etc/alertmanager/webhook_token'
        send_resolved: false

  # High priority alerts
  - name: 'high-priority'
    email_configs:
      - to: 'oncall@verteidiq.com'
        subject: 'High Priority Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ template "high_priority_alert.html" . }}
    
    slack_configs:
      - api_url_file: '/etc/alertmanager/slack_webhook'
        channel: '#alerts-high-priority'
        color: 'warning'
        title: 'High Priority Alert'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          {{ if .Annotations.runbook_url }}Runbook: {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}

  # SRE team for SLO violations
  - name: 'sre-team'
    email_configs:
      - to: 'sre@verteidiq.com'
        subject: 'SLO Alert: {{ .GroupLabels.alertname }}'
        body: |
          SLO Violation Detected
          
          {{ range .Alerts }}
          SLO: {{ .Labels.slo }}
          {{ if .Labels.burn_rate }}Burn Rate: {{ .Labels.burn_rate }}{{ end }}
          Description: {{ .Annotations.description }}
          Dashboard: {{ .Annotations.dashboard }}
          {{ end }}
    
    slack_configs:
      - api_url_file: '/etc/alertmanager/slack_webhook'
        channel: '#sre-slo-alerts'
        color: 'warning'
        title: 'SLO Violation'
        text: |
          {{ range .Alerts }}
          📊 *SLO:* {{ .Labels.slo }}
          🔥 *Burn Rate:* {{ .Labels.burn_rate | default "normal" }}
          📈 Dashboard: {{ .Annotations.dashboard }}
          {{ .Annotations.description }}
          {{ end }}

  # SRE urgent for fast burn SLO alerts
  - name: 'sre-urgent'
    pagerduty_configs:
      - service_key_file: '/etc/alertmanager/pagerduty_sre_key'
        severity: 'warning'
        description: 'SLO Fast Burn: {{ .CommonAnnotations.summary }}'
    
    slack_configs:
      - api_url_file: '/etc/alertmanager/slack_webhook'
        channel: '#sre-urgent'
        color: 'danger'
        title: '🔥 SLO Fast Burn Alert'
        text: |
          @here Fast burn rate detected!
          {{ range .Alerts }}
          📊 *SLO:* {{ .Labels.slo }}
          🔥 *Burn Rate:* {{ .Labels.burn_rate }}
          ⏰ *Error Budget Impact:* High
          📈 Dashboard: {{ .Annotations.dashboard }}
          {{ end }}

  # Compliance team for SOC2 issues
  - name: 'compliance-team'
    email_configs:
      - to: 'compliance@verteidiq.com,legal@verteidiq.com'
        subject: 'Compliance Alert: {{ .GroupLabels.alertname }}'
        body: |
          Compliance Issue Detected
          
          {{ range .Alerts }}
          Compliance Framework: {{ .Labels.compliance_impact }}
          Control: {{ .Labels.control_id | default "N/A" }}
          Description: {{ .Annotations.description }}
          {{ if .Annotations.runbook_url }}Remediation: {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}

  # DevOps security team
  - name: 'devops-security'
    email_configs:
      - to: 'devops@verteidiq.com,security@verteidiq.com'
        subject: 'Infrastructure Security Alert: {{ .GroupLabels.alertname }}'
    
    slack_configs:
      - api_url_file: '/etc/alertmanager/slack_webhook'
        channel: '#devops-security'
        color: 'warning'
        title: 'Infrastructure Security Alert'

  # Operations team for general monitoring
  - name: 'ops-team'
    email_configs:
      - to: 'ops@verteidiq.com'
        subject: 'Ops Alert: {{ .GroupLabels.alertname }}'
    
    slack_configs:
      - api_url_file: '/etc/alertmanager/slack_webhook'
        channel: '#ops-alerts'
        color: 'good'
        title: 'Operations Alert'

  # Development team for non-production alerts
  - name: 'dev-team'
    slack_configs:
      - api_url_file: '/etc/alertmanager/slack_webhook'
        channel: '#dev-alerts'
        color: 'good'
        title: 'Development Alert'
        text: |
          {{ range .Alerts }}
          Environment: {{ .Labels.environment }}
          {{ .Annotations.summary }}
          {{ end }}

# Time-based routing for after-hours escalation
time_intervals:
  - name: 'business_hours'
    time_intervals:
      - times:
          - start_time: '09:00'
            end_time: '17:00'
        weekdays: ['monday:friday']
        location: 'America/New_York'

  - name: 'weekends'
    time_intervals:
      - weekdays: ['saturday', 'sunday']