apiVersion: apps/v1
kind: Deployment
metadata:
  name: xorb-api
spec:
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xorb-worker
spec:
  template:
    spec:
      containers:
      - name: worker
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xorb-orchestrator
spec:
  template:
    spec:
      containers:
      - name: orchestrator
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"