apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: xorb-dev

resources:
- ../base

namespace: xorb-dev

namePrefix: dev-

commonLabels:
  xorb.ai/environment: dev
  
commonAnnotations:
  xorb.ai/managed-by: kustomize
  xorb.ai/environment: dev

images:
- name: xorb/api
  newTag: "develop"
- name: xorb/worker
  newTag: "develop"
- name: xorb/orchestrator
  newTag: "develop"

replicas:
- name: xorb-api
  count: 1  # Minimal for dev
- name: xorb-worker
  count: 2
- name: xorb-orchestrator
  count: 1

configMapGenerator:
- name: xorb-config
  behavior: merge
  literals:
  - XORB_ENVIRONMENT=development
  - XORB_LOG_LEVEL=DEBUG
  - XORB_DEBUG=true
  - TEMPORAL_HOST=dev-temporal-frontend.xorb-dev.svc.cluster.local:7233
  - REDIS_URL=redis://dev-redis-master.xorb-dev.svc.cluster.local:6379
  - QDRANT_URL=http://dev-qdrant.xorb-dev.svc.cluster.local:6333
  - NEO4J_URI=bolt://dev-neo4j.xorb-dev.svc.cluster.local:7687
  - NATS_URL=nats://dev-nats.xorb-dev.svc.cluster.local:4222
  - MAX_CONCURRENT_CAMPAIGNS=2
  - MAX_AGENTS_PER_CAMPAIGN=5
  - WORKER_CONCURRENCY=2
  - AGENT_POOL_SIZE=4

patches:
- target:
    kind: Deployment
    name: xorb-api
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "100m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "256Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "500m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "512Mi"
    
- target:
    kind: Deployment
    name: xorb-worker
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "200m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "512Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "1"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "1Gi"

- target:
    kind: Deployment
    name: xorb-orchestrator
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "100m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "256Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "500m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "512Mi"