apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: xorb-dev

resources:
- ../base

namespace: xorb-dev

namePrefix: dev-

commonLabels:
  xorb.ai/environment: dev
  
commonAnnotations:
  xorb.ai/managed-by: kustomize
  xorb.ai/environment: dev

images:
- name: xorb/api
  newTag: "develop"
- name: xorb/worker
  newTag: "develop"
- name: xorb/orchestrator
  newTag: "develop"

replicas:
- name: xorb-api
  count: 1
- name: xorb-worker
  count: 2
- name: xorb-orchestrator
  count: 1

configMapGenerator:
- name: xorb-config
  behavior: merge
  literals:
  - XORB_ENVIRONMENT=development
  - XORB_LOG_LEVEL=DEBUG
  - XORB_DEBUG=true
  - MAX_CONCURRENT_AGENTS=4
  - MAX_CONCURRENT_CAMPAIGNS=2
  - WORKER_CONCURRENCY=2
  - AGENT_POOL_SIZE=4

patchesStrategicMerge:
- dev-patches.yaml