# Security-focused alerting rules for PTaaS platform
# Focuses on threat detection and security incident response

groups:
  - name: security.authentication
    interval: 30s
    rules:
      # Multiple failed login attempts
      - alert: MultipleFailedLogins
        expr: |
          increase(authentication_attempts_total{outcome="failure"}[5m]) > 10
        for: 0m
        labels:
          severity: warning
          category: authentication
          security_event: brute_force_attempt
        annotations:
          summary: "Multiple failed login attempts detected"
          description: "{{ $value }} failed login attempts in the last 5 minutes from {{ $labels.source_ip }}"
          remediation: "Review access logs and consider IP blocking"
          runbook_url: "https://runbook.verteidiq.com/security/authentication-attacks"

      # Unusual login patterns
      - alert: UnusualLoginPattern
        expr: |
          (
            hour() < 6 or hour() > 22
          ) and
          increase(authentication_attempts_total{outcome="success"}[10m]) > 5
        for: 0m
        labels:
          severity: warning
          category: authentication
          security_event: unusual_access_pattern
        annotations:
          summary: "Unusual login pattern detected"
          description: "{{ $value }} successful logins during off-hours ({{ $labels.hour }}:XX)"
          remediation: "Verify legitimacy of after-hours access"

      # Privileged account usage
      - alert: PrivilegedAccountActivity
        expr: |
          increase(audit_events_total{user_role="admin",action!~"read|view"}[15m]) > 0
        for: 0m
        labels:
          severity: high
          category: privilege_escalation
          security_event: admin_action
        annotations:
          summary: "Privileged account activity detected"
          description: "Admin user {{ $labels.user_id }} performed {{ $labels.action }} on {{ $labels.resource }}"
          remediation: "Verify admin action was authorized and legitimate"

  - name: security.access_control
    interval: 30s
    rules:
      # Unauthorized access attempts
      - alert: UnauthorizedAccessAttempt
        expr: |
          increase(authorization_failures_total[5m]) > 20
        for: 2m
        labels:
          severity: warning
          category: access_control
          security_event: unauthorized_access
        annotations:
          summary: "High rate of unauthorized access attempts"
          description: "{{ $value }} authorization failures in 5 minutes from {{ $labels.source_ip }}"
          remediation: "Review access patterns and consider rate limiting"

      # Tenant isolation violations
      - alert: TenantIsolationViolation
        expr: |
          increase(tenant_isolation_violations_total[1m]) > 0
        for: 0m
        labels:
          severity: critical
          category: data_breach
          security_event: tenant_isolation_breach
          compliance_impact: soc2
        annotations:
          summary: "CRITICAL: Tenant isolation violation detected"
          description: "Potential cross-tenant data access: {{ $labels.violation_type }}"
          immediate_action: "Stop processing, investigate data breach potential"
          runbook_url: "https://runbook.verteidiq.com/security/tenant-isolation-breach"

      # Excessive permissions usage
      - alert: ExcessivePermissionsUsage
        expr: |
          (
            increase(api_requests_total{endpoint=~"/admin/.*"}[1h]) /
            increase(api_requests_total[1h])
          ) > 0.1
        for: 15m
        labels:
          severity: warning
          category: privilege_abuse
          security_event: excessive_admin_usage
        annotations:
          summary: "Excessive administrative permissions usage"
          description: "{{ $value | humanizePercentage }} of API requests are admin operations"
          remediation: "Review admin access patterns and principle of least privilege"

  - name: security.data_protection
    interval: 30s
    rules:
      # Unusual data access patterns
      - alert: UnusualDataAccess
        expr: |
          increase(data_access_events_total[10m]) > 
          quantile(0.95, increase(data_access_events_total[10m])[24h:1h]) * 2
        for: 5m
        labels:
          severity: warning
          category: data_access
          security_event: data_exfiltration_risk
        annotations:
          summary: "Unusual data access pattern detected"
          description: "Data access volume is {{ $value }}x higher than normal"
          remediation: "Investigate potential data exfiltration attempt"

      # Encryption failures
      - alert: EncryptionFailure
        expr: |
          increase(encryption_failures_total[5m]) > 0
        for: 0m
        labels:
          severity: high
          category: data_protection
          security_event: encryption_failure
          compliance_impact: gdpr
        annotations:
          summary: "Data encryption failure detected"
          description: "{{ $value }} encryption failures for {{ $labels.data_type }}"
          immediate_action: "Stop processing sensitive data until encryption is restored"
          runbook_url: "https://runbook.verteidiq.com/security/encryption-failure"

      # Sensitive data exposure
      - alert: SensitiveDataExposure
        expr: |
          increase(data_leakage_detection_total[1m]) > 0
        for: 0m
        labels:
          severity: critical
          category: data_breach
          security_event: sensitive_data_exposure
          compliance_impact: all
        annotations:
          summary: "CRITICAL: Sensitive data exposure detected"
          description: "Potential sensitive data leakage: {{ $labels.data_pattern }}"
          immediate_action: "Immediately contain and investigate data breach"
          runbook_url: "https://runbook.verteidiq.com/security/data-breach-response"

  - name: security.network
    interval: 30s
    rules:
      # DDoS attack detection
      - alert: DDoSAttack
        expr: |
          rate(http_requests_total[1m]) > 1000
        for: 1m
        labels:
          severity: high
          category: network_attack
          security_event: ddos_attack
        annotations:
          summary: "Potential DDoS attack detected"
          description: "Request rate is {{ $value }} requests/second, exceeding threshold"
          remediation: "Enable DDoS protection and analyze traffic patterns"
          runbook_url: "https://runbook.verteidiq.com/security/ddos-response"

      # Suspicious IP activity
      - alert: SuspiciousIPActivity
        expr: |
          increase(requests_from_blacklisted_ips_total[5m]) > 0
        for: 0m
        labels:
          severity: warning
          category: network_security
          security_event: blacklisted_ip_access
        annotations:
          summary: "Traffic from blacklisted IP detected"
          description: "{{ $value }} requests from blacklisted IP {{ $labels.source_ip }}"
          remediation: "Block IP and investigate attack patterns"

      # Geographic anomaly detection
      - alert: GeographicAnomalyDetection
        expr: |
          increase(requests_from_unusual_location_total[15m]) > 50
        for: 5m
        labels:
          severity: warning
          category: geographic_anomaly
          security_event: unusual_geographic_access
        annotations:
          summary: "Unusual geographic access pattern"
          description: "{{ $value }} requests from unusual location {{ $labels.country }}"
          remediation: "Verify legitimate business access from new geographic region"

  - name: security.application
    interval: 30s
    rules:
      # SQL injection attempts
      - alert: SQLInjectionAttempt
        expr: |
          increase(sql_injection_attempts_total[5m]) > 0
        for: 0m
        labels:
          severity: high
          category: injection_attack
          security_event: sql_injection
        annotations:
          summary: "SQL injection attempt detected"
          description: "{{ $value }} SQL injection attempts from {{ $labels.source_ip }}"
          immediate_action: "Block source IP and review application security"
          runbook_url: "https://runbook.verteidiq.com/security/injection-attacks"

      # XSS attempts
      - alert: XSSAttempt
        expr: |
          increase(xss_attempts_total[5m]) > 0
        for: 0m
        labels:
          severity: warning
          category: injection_attack
          security_event: xss_attempt
        annotations:
          summary: "Cross-site scripting attempt detected"
          description: "{{ $value }} XSS attempts targeting {{ $labels.endpoint }}"
          remediation: "Review input validation and output encoding"

      # File upload attacks
      - alert: MaliciousFileUpload
        expr: |
          increase(malicious_file_uploads_total[1m]) > 0
        for: 0m
        labels:
          severity: high
          category: malware
          security_event: malicious_file_upload
        annotations:
          summary: "Malicious file upload detected"
          description: "{{ $value }} malicious files uploaded: {{ $labels.file_type }}"
          immediate_action: "Quarantine files and scan for malware"
          runbook_url: "https://runbook.verteidiq.com/security/malware-response"

  - name: security.compliance
    interval: 60s
    rules:
      # SOC2 control failures
      - alert: SOC2ControlFailure
        expr: |
          increase(soc2_control_failures_total[1h]) > 0
        for: 0m
        labels:
          severity: high
          category: compliance
          security_event: soc2_control_failure
          compliance_impact: soc2
        annotations:
          summary: "SOC2 control failure detected"
          description: "Control {{ $labels.control_id }} failed: {{ $labels.failure_reason }}"
          remediation: "Immediately address control failure and document remediation"
          runbook_url: "https://runbook.verteidiq.com/compliance/soc2-control-failure"

      # Audit log tampering
      - alert: AuditLogTampering
        expr: |
          increase(audit_log_integrity_violations_total[5m]) > 0
        for: 0m
        labels:
          severity: critical
          category: audit_tampering
          security_event: audit_log_tampering
          compliance_impact: all
        annotations:
          summary: "CRITICAL: Audit log tampering detected"
          description: "Audit log integrity violation: {{ $labels.violation_type }}"
          immediate_action: "Secure audit logs and investigate tampering attempt"
          runbook_url: "https://runbook.verteidiq.com/security/audit-tampering"

      # Data retention violations
      - alert: DataRetentionViolation
        expr: |
          increase(data_retention_violations_total[24h]) > 0
        for: 0m
        labels:
          severity: warning
          category: compliance
          security_event: data_retention_violation
          compliance_impact: gdpr
        annotations:
          summary: "Data retention policy violation"
          description: "{{ $value }} data retention violations for {{ $labels.data_type }}"
          remediation: "Review and enforce data retention policies"

  - name: security.infrastructure
    interval: 60s
    rules:
      # Container security violations
      - alert: ContainerSecurityViolation
        expr: |
          increase(container_security_violations_total[5m]) > 0
        for: 0m
        labels:
          severity: warning
          category: infrastructure_security
          security_event: container_security_violation
        annotations:
          summary: "Container security violation detected"
          description: "{{ $labels.violation_type }} in container {{ $labels.container_name }}"
          remediation: "Review container security policies and image scanning"

      # Vulnerability scanning alerts
      - alert: HighSeverityVulnerability
        expr: |
          increase(vulnerabilities_detected_total{severity="critical"}[24h]) > 0
        for: 0m
        labels:
          severity: high
          category: vulnerability_management
          security_event: critical_vulnerability
        annotations:
          summary: "Critical vulnerability detected"
          description: "{{ $value }} critical vulnerabilities found in {{ $labels.component }}"
          immediate_action: "Prioritize patching critical vulnerabilities"
          runbook_url: "https://runbook.verteidiq.com/security/vulnerability-response"

      # Secrets exposure
      - alert: SecretsExposure
        expr: |
          increase(secrets_exposure_total[1m]) > 0
        for: 0m
        labels:
          severity: critical
          category: secrets_management
          security_event: secrets_exposure
        annotations:
          summary: "CRITICAL: Secrets exposure detected"
          description: "{{ $labels.secret_type }} exposed in {{ $labels.location }}"
          immediate_action: "Rotate exposed secrets immediately"
          runbook_url: "https://runbook.verteidiq.com/security/secrets-exposure"

  - name: security.response
    interval: 30s
    rules:
      # Security alert fatigue
      - alert: SecurityAlertFatigue
        expr: |
          increase(security_alerts_total[1h]) > 100
        for: 15m
        labels:
          severity: warning
          category: alert_management
          security_event: alert_fatigue
        annotations:
          summary: "High volume of security alerts"
          description: "{{ $value }} security alerts in the last hour"
          remediation: "Review alert tuning and reduce false positives"

      # Unacknowledged security alerts
      - alert: UnacknowledgedSecurityAlerts
        expr: |
          security_alerts_unacknowledged > 10
        for: 30m
        labels:
          severity: warning
          category: incident_response
          security_event: unacknowledged_alerts
        annotations:
          summary: "Multiple unacknowledged security alerts"
          description: "{{ $value }} security alerts remain unacknowledged"
          remediation: "Review security team availability and escalation procedures"

      # Security incident escalation
      - alert: SecurityIncidentEscalation
        expr: |
          security_incidents_open{severity="critical"} > 0
        for: 60m
        labels:
          severity: high
          category: incident_management
          security_event: incident_escalation
        annotations:
          summary: "Critical security incident requires escalation"
          description: "Critical security incident {{ $labels.incident_id }} open for over 1 hour"
          immediate_action: "Escalate to security leadership and engage external resources if needed"