apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pgvector.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "pgvector.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: xorb-api
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: xorb-worker
    ports:
    - protocol: TCP
      port: 5432
