apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ray-cluster.fullname" . }}-worker
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ray-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: ray-worker
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.rayWorkers.replicaCount }}
  selector:
    matchLabels:
      {{- include "ray-cluster.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ray-worker
  template:
    metadata:
      labels:
        {{- include "ray-cluster.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ray-worker
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.commonAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ray-cluster.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.rayWorkers.securityContext | nindent 8 }}
      {{- with .Values.rayWorkers.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rayWorkers.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rayWorkers.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ray-worker
          securityContext:
            {{- toYaml .Values.rayWorkers.containerSecurityContext | nindent 12 }}
          image: {{ .Values.rayWorkers.image.registry }}/{{ .Values.rayWorkers.image.repository }}:{{ .Values.rayWorkers.image.tag }}
          imagePullPolicy: {{ .Values.rayWorkers.image.pullPolicy }}
          command:
            - ray
            - start
            - --address={{ include "ray-cluster.fullname" . }}-head-svc:{{ .Values.rayHead.rayStartParams.port | default 6379 }}
            {{- range $key, $value := .Values.rayWorkers.rayStartParams }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          env:
            - name: RAY_ADDRESS
              value: "{{ include "ray-cluster.fullname" . }}-head-svc:{{ .Values.rayHead.rayStartParams.port | default 6379 }}"
            - name: RAY_CLUSTER_NAME
              value: {{ .Values.rayCluster.name }}
            - name: RAY_NODE_TYPE
              value: "worker"
            {{- with .Values.rayWorkers.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.rayWorkers.resources | nindent 12 }}
          volumeMounts:
            - name: ray-logs
              mountPath: /tmp/ray
            - name: config-volume
              mountPath: /workspace/ray.yaml
              subPath: ray.yaml
              readOnly: true
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            exec:
              command:
                - ray
                - status
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
            successThreshold: {{ .Values.probes.startup.successThreshold }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            exec:
              command:
                - ray
                - status
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            successThreshold: {{ .Values.probes.liveness.successThreshold }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            exec:
              command:
                - ray
                - status
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
            successThreshold: {{ .Values.probes.readiness.successThreshold }}
          {{- end }}
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: ray-logs
          emptyDir: {}
        - name: config-volume
          configMap:
            name: {{ include "ray-cluster.fullname" . }}-config
            items:
            - key: ray.yaml
              path: ray.yaml
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 60