# SLO-based alerting rules for PTaaS platform
# Based on Google SRE practices with multi-burn-rate alerts

groups:
  - name: slo.api.availability
    interval: 30s
    rules:
      # API Availability SLO: 99.9% (43.2 minutes downtime per month)

      # Calculate error budget burn rate
      - record: slo:api_availability_5m
        expr: 1 - (rate(http_requests_total{job="ptaas-api",code!~"5.."}[5m]) / rate(http_requests_total{job="ptaas-api"}[5m]))

      - record: slo:api_availability_30m
        expr: 1 - (rate(http_requests_total{job="ptaas-api",code!~"5.."}[30m]) / rate(http_requests_total{job="ptaas-api"}[30m]))

      - record: slo:api_availability_1h
        expr: 1 - (rate(http_requests_total{job="ptaas-api",code!~"5.."}[1h]) / rate(http_requests_total{job="ptaas-api"}[1h]))

      - record: slo:api_availability_6h
        expr: 1 - (rate(http_requests_total{job="ptaas-api",code!~"5.."}[6h]) / rate(http_requests_total{job="ptaas-api"}[6h]))

      # Multi-burn-rate alerts
      # Fast burn: 2% budget in 1 hour (14.4x burn rate)
      - alert: APIAvailabilitySLOFastBurn
        expr: |
          (
            slo:api_availability_5m > (14.4 * 0.001)
            and
            slo:api_availability_1h > (14.4 * 0.001)
          )
        for: 2m
        labels:
          severity: critical
          slo: api_availability
          burn_rate: fast
        annotations:
          summary: "API availability SLO fast burn detected"
          description: "API availability is burning error budget at 14.4x rate. Current 5m error rate: {{ $value | humanizePercentage }}"
          runbook_url: "https://runbook.verteidiq.com/slo/api-availability"
          dashboard: "https://grafana.verteidiq.com/d/api-availability"

      # Slow burn: 10% budget in 6 hours (6x burn rate)
      - alert: APIAvailabilitySLOSlowBurn
        expr: |
          (
            slo:api_availability_30m > (6 * 0.001)
            and
            slo:api_availability_6h > (6 * 0.001)
          )
        for: 15m
        labels:
          severity: warning
          slo: api_availability
          burn_rate: slow
        annotations:
          summary: "API availability SLO slow burn detected"
          description: "API availability is burning error budget at 6x rate. Current 30m error rate: {{ $value | humanizePercentage }}"
          runbook_url: "https://runbook.verteidiq.com/slo/api-availability"

  - name: slo.api.latency
    interval: 30s
    rules:
      # API Latency SLO: 95% of requests < 300ms, 50% < 50ms

      # P95 latency SLO (300ms)
      - record: slo:api_latency_p95_5m
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="ptaas-api"}[5m]))

      - record: slo:api_latency_p95_30m
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="ptaas-api"}[30m]))

      # P50 latency SLO (50ms)
      - record: slo:api_latency_p50_5m
        expr: histogram_quantile(0.50, rate(http_request_duration_seconds_bucket{job="ptaas-api"}[5m]))

      # Calculate SLO violations
      - record: slo:api_latency_p95_violation_rate_5m
        expr: |
          (
            sum(rate(http_request_duration_seconds_bucket{job="ptaas-api",le="0.3"}[5m])) /
            sum(rate(http_request_duration_seconds_count{job="ptaas-api"}[5m]))
          ) < 0.95

      - alert: APILatencyP95SLOViolation
        expr: slo:api_latency_p95_5m > 0.3
        for: 5m
        labels:
          severity: warning
          slo: api_latency_p95
        annotations:
          summary: "API P95 latency SLO violation"
          description: "API P95 latency is {{ $value }}s, exceeding 300ms SLO"
          runbook_url: "https://runbook.verteidiq.com/slo/api-latency"

      - alert: APILatencyP50SLOViolation
        expr: slo:api_latency_p50_5m > 0.05
        for: 5m
        labels:
          severity: warning
          slo: api_latency_p50
        annotations:
          summary: "API P50 latency SLO violation"
          description: "API P50 latency is {{ $value }}s, exceeding 50ms SLO"
          runbook_url: "https://runbook.verteidiq.com/slo/api-latency"

  - name: slo.scan.success_rate
    interval: 30s
    rules:
      # Scan Success Rate SLO: 95% of scans complete successfully

      - record: slo:scan_success_rate_5m
        expr: |
          rate(scan_requests_total{status="success"}[5m]) /
          rate(scan_requests_total[5m])

      - record: slo:scan_success_rate_1h
        expr: |
          rate(scan_requests_total{status="success"}[1h]) /
          rate(scan_requests_total[1h])

      - alert: ScanSuccessRateSLOViolation
        expr: slo:scan_success_rate_5m < 0.95
        for: 10m
        labels:
          severity: warning
          slo: scan_success_rate
        annotations:
          summary: "Penetration test success rate SLO violation"
          description: "Penetration test success rate is {{ $value | humanizePercentage }}, below 95% SLO"
          runbook_url: "https://runbook.verteidiq.com/slo/pentest-success-rate"

  - name: slo.data_processing
    interval: 30s
    rules:
      # Data Processing Integrity SLO: 99.99% of data processed without errors

      - record: slo:data_processing_error_rate_5m
        expr: |
          rate(data_processing_errors_total[5m]) /
          rate(data_processing_total[5m])

      - alert: DataProcessingIntegritySLOViolation
        expr: slo:data_processing_error_rate_5m > 0.0001
        for: 2m
        labels:
          severity: critical
          slo: data_processing_integrity
        annotations:
          summary: "Data processing integrity SLO violation"
          description: "Data processing error rate is {{ $value | humanizePercentage }}, exceeding 0.01% SLO"
          runbook_url: "https://runbook.xorb.com/slo/data-processing"

  - name: slo.backup_recovery
    interval: 60s
    rules:
      # Backup Success SLO: 100% of scheduled backups complete successfully

      - record: slo:backup_success_rate_24h
        expr: |
          sum(increase(backup_jobs_total{status="success"}[24h])) /
          sum(increase(backup_jobs_total[24h]))

      - alert: BackupSuccessSLOViolation
        expr: slo:backup_success_rate_24h < 1.0
        for: 0m
        labels:
          severity: critical
          slo: backup_success
        annotations:
          summary: "Backup success SLO violation"
          description: "Backup success rate is {{ $value | humanizePercentage }}, below 100% SLO"
          runbook_url: "https://runbook.xorb.com/slo/backup-success"

  - name: slo.compliance_monitoring
    interval: 60s
    rules:
      # SOC2 Control Testing SLO: 100% of automated controls tested on schedule

      - record: slo:soc2_control_testing_compliance_24h
        expr: |
          sum(increase(soc2_control_tests_total{status="completed"}[24h])) /
          sum(increase(soc2_control_tests_scheduled_total[24h]))

      - alert: SOC2ControlTestingSLOViolation
        expr: slo:soc2_control_testing_compliance_24h < 1.0
        for: 0m
        labels:
          severity: high
          slo: soc2_control_testing
          compliance: soc2
        annotations:
          summary: "SOC2 control testing SLO violation"
          description: "SOC2 control testing compliance is {{ $value | humanizePercentage }}, below 100% SLO"
          runbook_url: "https://runbook.xorb.com/slo/soc2-compliance"

  - name: slo.security_response
    interval: 30s
    rules:
      # Security Incident Response SLO: 95% of security alerts acknowledged within 15 minutes

      - record: slo:security_response_time_p95_1h
        expr: histogram_quantile(0.95, rate(security_alert_response_duration_seconds_bucket[1h]))

      - alert: SecurityResponseTimeSLOViolation
        expr: slo:security_response_time_p95_1h > 900  # 15 minutes
        for: 5m
        labels:
          severity: high
          slo: security_response_time
        annotations:
          summary: "Security response time SLO violation"
          description: "Security alert P95 response time is {{ $value }}s, exceeding 15 minute SLO"
          runbook_url: "https://runbook.xorb.com/slo/security-response"

  - name: slo.tenant_isolation
    interval: 30s
    rules:
      # Tenant Isolation SLO: 100% of tenant queries properly isolated

      - record: slo:tenant_isolation_violation_rate_5m
        expr: |
          rate(tenant_isolation_violations_total[5m]) /
          rate(database_queries_total[5m])

      - alert: TenantIsolationSLOViolation
        expr: slo:tenant_isolation_violation_rate_5m > 0
        for: 0m
        labels:
          severity: critical
          slo: tenant_isolation
          security: high
        annotations:
          summary: "Tenant isolation SLO violation"
          description: "Tenant isolation violations detected: {{ $value | humanizePercentage }} of queries"
          runbook_url: "https://runbook.xorb.com/slo/tenant-isolation"
          immediate_action: "Investigate and contain potential data breach"
