apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: xorb-production

resources:
- ../base
- production-networkpolicies.yaml
- production-poddisruptionbudgets.yaml

namespace: xorb-prod

namePrefix: prod-

commonLabels:
  xorb.ai/environment: production
  
commonAnnotations:
  xorb.ai/managed-by: kustomize
  xorb.ai/environment: production
  xorb.ai/optimized-for: epyc-7702

images:
- name: xorb/api
  newTag: "2.0.0"
- name: xorb/worker
  newTag: "2.0.0"
- name: xorb/orchestrator
  newTag: "2.0.0"

# EPYC-optimized replica counts
replicas:
- name: xorb-api
  count: 4
- name: xorb-worker
  count: 8
- name: xorb-orchestrator
  count: 3

configMapGenerator:
- name: xorb-config
  behavior: merge
  literals:
  - XORB_ENVIRONMENT=production
  - XORB_LOG_LEVEL=INFO
  - XORB_DEBUG=false
  - MAX_CONCURRENT_AGENTS=32
  - MAX_CONCURRENT_CAMPAIGNS=10
  - WORKER_CONCURRENCY=16
  - AGENT_POOL_SIZE=64

patchesStrategicMerge:
- production-patches.yaml