apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: xorb-api-pdb
  namespace: xorb-prod
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: xorb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: xorb
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: xorb-worker-pdb
  namespace: xorb-prod
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: xorb
spec:
  minAvailable: 4
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/part-of: xorb
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: xorb-orchestrator-pdb
  namespace: xorb-prod
  labels:
    app.kubernetes.io/component: orchestrator
    app.kubernetes.io/part-of: xorb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: orchestrator
      app.kubernetes.io/part-of: xorb
---