apiVersion: apps/v1
kind: Deployment
metadata:
  name: xorb-api
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        node.kubernetes.io/cpu-family: "EPYC"
        xorb.ai/optimized-for: epyc-7702
      containers:
      - name: api
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xorb-worker
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        node.kubernetes.io/cpu-family: "EPYC"
        xorb.ai/optimized-for: epyc-7702
      containers:
      - name: worker
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "4"
            memory: "6Gi"
        env:
        - name: WORKER_CONCURRENCY
          value: "16"
        - name: AGENT_POOL_SIZE
          value: "64"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xorb-orchestrator
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        node.kubernetes.io/cpu-family: "EPYC"
        xorb.ai/optimized-for: epyc-7702
      containers:
      - name: orchestrator
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "3"
            memory: "4Gi"
        env:
        - name: MAX_CONCURRENT_CAMPAIGNS
          value: "10"
        - name: MAX_AGENTS_PER_CAMPAIGN
          value: "32"