apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: xorb-epyc-advanced-rules
  namespace: xorb-prod
  labels:
    app.kubernetes.io/name: xorb
    app.kubernetes.io/component: monitoring
    prometheus: kube-prometheus
spec:
  groups:
  - name: xorb.epyc.performance.rules
    interval: 15s
    rules:
    - alert: XorbEPYCCCXImbalance
      expr: max(epyc_ccx_utilization_percent) - min(epyc_ccx_utilization_percent) > 40
      for: 5m
      labels:
        severity: warning
        component: infrastructure
        optimization: ccx-balancing
      annotations:
        summary: "EPYC CCX load imbalance detected"
        description: "CCX utilization variance is {{ $value }}% on {{ $labels.instance }}. Consider workload redistribution."
        runbook_url: "https://docs.xorb.ai/runbooks/epyc-ccx-imbalance"
        
    - alert: XorbEPYCL3CacheMissHigh
      expr: epyc_l3_cache_miss_ratio > 0.15
      for: 10m
      labels:
        severity: warning
        component: performance
        optimization: cache-efficiency
      annotations:
        summary: "High L3 cache miss ratio detected"
        description: "L3 cache miss ratio is {{ $value | humanizePercentage }} on CCX {{ $labels.ccx }}. Review thread placement strategy."
        
    - alert: XorbEPYCMemoryBandwidthSaturation
      expr: epyc_memory_bandwidth_utilization_percent > 85
      for: 5m
      labels:
        severity: warning
        component: memory
        optimization: bandwidth-management
      annotations:
        summary: "EPYC memory bandwidth near saturation"
        description: "Memory bandwidth utilization is {{ $value | humanizePercentage }} on NUMA node {{ $labels.numa_node }}"
        
    - alert: XorbEPYCThermalThrottling
      expr: epyc_thermal_throttling_active == 1
      for: 1m
      labels:
        severity: critical
        component: thermal
        optimization: thermal-management
      annotations:
        summary: "EPYC thermal throttling active"
        description: "Thermal throttling detected on node {{ $labels.instance }}. CPU performance may be degraded."
        
    - alert: XorbEPYCNUMALocalityLow
      expr: epyc_numa_memory_locality_ratio < 0.7
      for: 15m
      labels:
        severity: warning
        component: numa
        optimization: memory-locality
      annotations:
        summary: "Low NUMA memory locality ratio"
        description: "NUMA memory locality is {{ $value | humanizePercentage }} on {{ $labels.instance }}. Review process placement."

  - name: xorb.dqn.performance.rules
    interval: 30s
    rules:
    - alert: XorbDQNConvergenceSlowing
      expr: rate(xorb_dqn_q_value_convergence[10m]) < 0.01
      for: 20m
      labels:
        severity: warning
        component: reinforcement-learning
        optimization: dqn-tuning
      annotations:
        summary: "DQN convergence rate slowing"
        description: "DQN Q-value convergence rate is {{ $value }} on {{ $labels.instance }}. Consider hyperparameter adjustment."
        
    - alert: XorbDQNSelectionAccuracyLow
      expr: xorb_dqn_selection_accuracy_ratio < 0.8
      for: 30m
      labels:
        severity: warning
        component: reinforcement-learning
        optimization: agent-selection
      annotations:
        summary: "DQN agent selection accuracy below threshold"
        description: "Agent selection accuracy is {{ $value | humanizePercentage }}. Review training data quality."
        
    - alert: XorbDQNMemoryBufferFull
      expr: xorb_dqn_experience_buffer_utilization > 0.95
      for: 5m
      labels:
        severity: info
        component: reinforcement-learning
        optimization: memory-management
      annotations:
        summary: "DQN experience buffer near capacity"
        description: "Experience buffer utilization is {{ $value | humanizePercentage }}. Buffer rotation will begin soon."

  - name: xorb.backpressure.rules
    interval: 10s
    rules:
    - alert: XorbBackpressureHighPressure
      expr: epyc_backpressure_current_pressure_ratio > 0.8
      for: 2m
      labels:
        severity: warning
        component: resource-management
        optimization: backpressure-control
      annotations:
        summary: "High backpressure detected"
        description: "System pressure ratio is {{ $value | humanizePercentage }} on {{ $labels.instance }}"
        
    - alert: XorbBackpressureFrequentThrottling
      expr: rate(epyc_backpressure_throttle_actions_total[5m]) > 10
      for: 5m
      labels:
        severity: warning
        component: resource-management
        optimization: capacity-planning
      annotations:
        summary: "Frequent backpressure throttling"
        description: "Throttling rate is {{ $value }} actions/min. Consider scaling resources."

  - name: xorb.epyc.governor.rules
    interval: 30s
    rules:
    - alert: XorbEPYCGovernorStuckPerformance
      expr: epyc_cpu_governor_current{governor="performance"} == 1 and epyc_cpu_utilization_percent < 30
      for: 10m
      labels:
        severity: info
        component: power-management
        optimization: governor-tuning
      annotations:
        summary: "CPU governor stuck in performance mode"
        description: "CPU governor is in performance mode with low utilization ({{ $value }}%) for extended period"
        
    - alert: XorbEPYCFrequencyScalingIssue
      expr: abs(epyc_cpu_frequency_current_mhz - epyc_cpu_frequency_target_mhz) > 200
      for: 5m
      labels:
        severity: warning
        component: performance
        optimization: frequency-scaling
      annotations:
        summary: "CPU frequency scaling issue detected"
        description: "CPU frequency deviation: target={{ $labels.target_mhz }}MHz, actual={{ $value }}MHz"

  - name: xorb.campaign.performance.rules
    interval: 60s
    rules:
    - record: xorb:campaign_success_rate_5m
      expr: rate(xorb_campaigns_successful_total[5m]) / rate(xorb_campaigns_total[5m])
      
    - record: xorb:epyc_optimal_campaigns_ratio
      expr: sum(rate(xorb_campaigns_successful_total{numa_optimized="true"}[5m])) / sum(rate(xorb_campaigns_total[5m]))
      
    - alert: XorbCampaignSuccessRateDecline
      expr: xorb:campaign_success_rate_5m < 0.7
      for: 15m
      labels:
        severity: warning
        component: orchestration
        optimization: campaign-tuning
      annotations:
        summary: "Campaign success rate declining"
        description: "Campaign success rate is {{ $value | humanizePercentage }} over last 5 minutes"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xorb-epyc-dashboard-config
  namespace: xorb-prod
  labels:
    grafana_dashboard: "1"
data:
  epyc-overview.json: |
    {
      "dashboard": {
        "title": "Xorb EPYC Performance Overview",
        "refresh": "10s",
        "tags": ["xorb", "epyc", "performance"]
      }
    }