apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xorb-api-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: xorb-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: xorb
    prometheus: kube-prometheus
spec:
  namespaceSelector:
    matchNames:
    - xorb-prod
    - xorb-staging
    - xorb-dev
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: xorb
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'xorb_api_.*'
      targetLabel: __tmp_xorb_metric
      replacement: 'true'
    - sourceLabels: [__name__]
      regex: 'http_requests_total'
      targetLabel: __tmp_http_metric
      replacement: 'true'
    - sourceLabels: [__name__]
      regex: 'http_request_duration_seconds.*'
      targetLabel: __tmp_http_duration_metric
      replacement: 'true'
    relabelings:
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: environment
      regex: 'xorb-(.*)'
      replacement: '${1}'
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
      targetLabel: instance
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xorb-worker-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: xorb-worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: xorb
    prometheus: kube-prometheus
spec:
  namespaceSelector:
    matchNames:
    - xorb-prod
    - xorb-staging
    - xorb-dev
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/part-of: xorb
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'xorb_worker_.*'
      targetLabel: __tmp_xorb_metric
      replacement: 'true'
    - sourceLabels: [__name__]
      regex: 'xorb_agent_.*'
      targetLabel: __tmp_agent_metric
      replacement: 'true'
    - sourceLabels: [__name__]
      regex: 'temporal_.*'
      targetLabel: __tmp_temporal_metric
      replacement: 'true'
    relabelings:
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: environment
      regex: 'xorb-(.*)'
      replacement: '${1}'
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
      targetLabel: instance
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xorb-orchestrator-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: xorb-orchestrator
    app.kubernetes.io/component: orchestrator
    app.kubernetes.io/part-of: xorb
    prometheus: kube-prometheus
spec:
  namespaceSelector:
    matchNames:
    - xorb-prod
    - xorb-staging
    - xorb-dev
  selector:
    matchLabels:
      app.kubernetes.io/component: orchestrator
      app.kubernetes.io/part-of: xorb
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'xorb_orchestrator_.*'
      targetLabel: __tmp_xorb_metric
      replacement: 'true'
    - sourceLabels: [__name__]
      regex: 'xorb_campaign_.*'
      targetLabel: __tmp_campaign_metric
      replacement: 'true'
    relabelings:
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: environment
      regex: 'xorb-(.*)'
      replacement: '${1}'
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
      targetLabel: instance
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: linkerd-proxy-xorb
  namespace: monitoring
  labels:
    app.kubernetes.io/name: linkerd-proxy
    app.kubernetes.io/part-of: xorb
    prometheus: kube-prometheus
spec:
  namespaceSelector:
    matchNames:
    - xorb-prod
    - xorb-staging
    - xorb-dev
  selector:
    matchLabels:
      app.kubernetes.io/part-of: xorb
  endpoints:
  - port: linkerd-admin
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    relabelings:
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: environment
      regex: 'xorb-(.*)'
      replacement: '${1}'
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_pod_container_name]
      targetLabel: container
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'request_total|response_total|response_latency_ms.*'
      targetLabel: __tmp_linkerd_metric
      replacement: 'true'
---