
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xorb-api
  namespace: xorb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xorb-api
  template:
    metadata:
      labels:
        app: xorb-api
    spec:
      containers:
      - name: xorb-api
        image: nginx:latest # Placeholder image
        ports:
        - containerPort: 80
