# Linkerd Control Plane Configuration for Xorb 2.0
# EPYC-optimized with enhanced security and observability

apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-config
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: controller
    linkerd.io/control-plane-ns: linkerd
data:
  global: |
    {
      "linkerdNamespace": "linkerd",
      "cniEnabled": true,
      "version": "stable-2.14.0",
      "identityContext": {
        "trustDomain": "cluster.local",
        "trustAnchorsPem": "",
        "issuanceLifetime": "24h0m0s",
        "clockSkewAllowance": "20s"
      },
      "autoInjectContext": null,
      "omitWebhookSideEffects": false,
      "clusterDomain": "cluster.local",
      "clusterNetworks": "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16",
      "proxy": {
        "proxyImage": {
          "name": "cr.l5d.io/linkerd/proxy",
          "version": "stable-2.14.0"
        },
        "proxyInitImage": {
          "name": "cr.l5d.io/linkerd/proxy-init",
          "version": "v2.0.0"
        },
        "controlPort": 4190,
        "ignoreInboundPorts": "",
        "ignoreOutboundPorts": "",
        "inboundPort": 4143,
        "adminPort": 4191,
        "outboundPort": 4140,
        "resource": {
          "requestCpu": "100m",
          "requestMemory": "128Mi",
          "limitCpu": "200m",
          "limitMemory": "256Mi"
        },
        "proxyUid": 2102,
        "logLevel": "warn,linkerd=info",
        "logFormat": "json",
        "disableExternalProfiles": false,
        "proxyVersion": "stable-2.14.0",
        "proxyInitImageVersion": "v2.0.0",
        "debugImage": {
          "name": "cr.l5d.io/linkerd/debug",
          "version": "stable-2.14.0"
        },
        "debugImageVersion": "stable-2.14.0",
        "imagePullPolicy": "IfNotPresent",
        "enableExternalProfile": true,
        "waitBeforeExitSeconds": 0,
        "requireIdentityOnInboundPorts": "",
        "opaquePorts": "25,587,3306,4444,5432,6379,9300,11211",
        "nativeSidecar": false,
        "requireTLSOnInboundPorts": "",
        "destinationGetNetworks": "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
      },
      "proxyInit": {
        "ignoreInboundPorts": "",
        "ignoreOutboundPorts": "",
        "xtMountPath": {
          "mountPath": "/run",
          "name": "linkerd-proxy-init-xtables-lock"
        },
        "runAsRoot": true
      }
    }
  install: |
    {
      "uuid": "xorb-linkerd-uuid-12345",
      "cliVersion": "stable-2.14.0",
      "flags": []
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-identity-trust-roots
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: identity
    linkerd.io/control-plane-ns: linkerd
data:
  # Trust anchor certificate for mTLS
  # This should be generated during Linkerd installation
  trust-anchor.crt: |
    -----BEGIN CERTIFICATE-----
    # Placeholder - replace with actual trust anchor certificate
    # Generated during linkerd install --cluster-name xorb-prod
    -----END CERTIFICATE-----
---
# Enhanced proxy injection configuration for Xorb services
apiVersion: v1
kind: ConfigMap
metadata:
  name: xorb-proxy-injector-config
  namespace: linkerd
  labels:
    app.kubernetes.io/part-of: xorb-linkerd
data:
  config.yaml: |
    proxy:
      # EPYC-optimized proxy resource settings
      resources:
        cpu:
          request: "100m"
          limit: "300m"  # Higher limit for EPYC burst capability
        memory:
          request: "128Mi"
          limit: "384Mi"  # More memory for high-throughput workloads
      # Enhanced logging for security intelligence platform
      logLevel: "info"
      logFormat: "json"
      # Proxy configuration for AI security workloads
      proxyMetadata:
        - name: "LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES"
          value: ".svc.cluster.local."
        - name: "LINKERD2_PROXY_INBOUND_DEFAULT_POLICY"
          value: "all-authenticated"  # Require authentication by default
        - name: "LINKERD2_PROXY_OUTBOUND_DEFAULT_POLICY"  
          value: "all-authenticated"
        # Performance tuning for EPYC
        - name: "LINKERD2_PROXY_INBOUND_CONNECT_TIMEOUT"
          value: "10s"
        - name: "LINKERD2_PROXY_OUTBOUND_CONNECT_TIMEOUT"
          value: "10s"
        - name: "LINKERD2_PROXY_INBOUND_PORTS_DISABLE_PROTOCOL_DETECTION"
          value: "8000,8080,9090"  # Disable detection for known HTTP ports
      opaquePorts: "5432,6379,6333,7687,4222,7233"  # Database and message broker ports
---