apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: xorb-api-server
  namespace: xorb-prod
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: xorb
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: xorb
  port: 8000
  proxyProtocol: HTTP/2
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: xorb-orchestrator-server
  namespace: xorb-prod
  labels:
    app.kubernetes.io/component: orchestrator
    app.kubernetes.io/part-of: xorb
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: orchestrator
      app.kubernetes.io/part-of: xorb
  port: 8080
  proxyProtocol: HTTP/2
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: xorb-worker-server
  namespace: xorb-prod
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: xorb
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/part-of: xorb
  port: 9090
  proxyProtocol: HTTP/2
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: xorb-api-authorization
  namespace: xorb-prod
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: xorb
spec:
  server:
    name: xorb-api-server
  requiredRoutes:
  - pathRegex: /api/.*
    methods: ["GET", "POST", "PUT", "DELETE"]
  - pathRegex: /health
    methods: ["GET"]
  - pathRegex: /ready
    methods: ["GET"]
  - pathRegex: /metrics
    methods: ["GET"]
  client:
    meshTLS:
      identities:
      - xorb-orchestrator.xorb-prod.serviceaccount.identity.linkerd.cluster.local
      - xorb-worker.xorb-prod.serviceaccount.identity.linkerd.cluster.local
      - nginx-ingress.ingress-nginx.serviceaccount.identity.linkerd.cluster.local
      - prometheus.monitoring.serviceaccount.identity.linkerd.cluster.local
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: xorb-orchestrator-authorization
  namespace: xorb-prod
  labels:
    app.kubernetes.io/component: orchestrator
    app.kubernetes.io/part-of: xorb
spec:
  server:
    name: xorb-orchestrator-server
  requiredRoutes:
  - pathRegex: /orchestrator/.*
    methods: ["GET", "POST", "PUT", "DELETE"]
  - pathRegex: /health
    methods: ["GET"]
  - pathRegex: /ready
    methods: ["GET"]
  - pathRegex: /metrics
    methods: ["GET"]
  client:
    meshTLS:
      identities:
      - xorb-api.xorb-prod.serviceaccount.identity.linkerd.cluster.local
      - xorb-worker.xorb-prod.serviceaccount.identity.linkerd.cluster.local
      - prometheus.monitoring.serviceaccount.identity.linkerd.cluster.local
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: xorb-worker-authorization
  namespace: xorb-prod
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: xorb
spec:
  server:
    name: xorb-worker-server
  requiredRoutes:
  - pathRegex: /health
    methods: ["GET"]
  - pathRegex: /ready
    methods: ["GET"]
  - pathRegex: /metrics
    methods: ["GET"]
  client:
    meshTLS:
      identities:
      - xorb-api.xorb-prod.serviceaccount.identity.linkerd.cluster.local
      - xorb-orchestrator.xorb-prod.serviceaccount.identity.linkerd.cluster.local
      - prometheus.monitoring.serviceaccount.identity.linkerd.cluster.local
---
apiVersion: policy.linkerd.io/v1alpha1
kind: HTTPRoute
metadata:
  name: xorb-api-route
  namespace: xorb-prod
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: xorb
spec:
  parentRefs:
  - name: xorb-api-server
    kind: Server
    group: policy.linkerd.io
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/campaigns
      method: POST
    timeouts:
      request: 30s
    backendRefs:
    - name: xorb-api
      port: 8000
      weight: 100
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/campaigns
      method: GET
    timeouts:
      request: 10s
    backendRefs:
    - name: xorb-api
      port: 8000
      weight: 100
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/agents
    timeouts:
      request: 15s
    backendRefs:
    - name: xorb-api
      port: 8000
      weight: 100
  - matches:
    - path:
        type: Exact
        value: /health
    - path:
        type: Exact
        value: /ready
    - path:
        type: Exact
        value: /metrics
    timeouts:
      request: 5s
    backendRefs:
    - name: xorb-api
      port: 8000
      weight: 100
---