[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xorb-core"
version = "2.0.0"
description = "Core library for the Xorb 2.0 platform, containing shared business logic, models, and clients."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [
  { name="Gemini", email="gemini@google.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    # --- Core Framework ---
    "pydantic>=2.5.0",
    "pydantic-settings>=2.1.0",
    "pydantic-ai",
    "httpx>=0.25.2",
    "requests>=2.32.3",
    "PyYAML>=6.0.1",
    "structlog>=23.2.0",
    "python-dotenv>=1.0.1",
    "cryptography>=41.0.8",
    "starlette-prometheus",

    # --- AI/ML & LLM Engine ---
    "litellm",          # Unified LLM API
    "langgraph>=0.2.55", # For building complex agentic RAG
    "openai>=1.61.0",
    "tiktoken>=0.5.2",
    "numpy>=1.25.2",

    # --- Knowledge Fabric & Data ---
    "neo4j>=5.15.0",
    "pgvector",         # Postgres vector extension
    "asyncpg>=0.29.0",  # High-performance Postgres driver
    "redis>=5.0.1",

    # --- External Tooling & Security ---
    "beautifulsoup4>=4.12.3",
    "dnspython>=2.4.2",
    "shodan>=1.30.1",
    "censys>=2.2.8",
    "tavily-python>=0.3.0",
    "duckduckgo-search>=3.0.0",
    "exa-py>=1.0.0",
]

[project.urls]
"Homepage" = "https://github.com/losa201/Xorb"
"Bug Tracker" = "https://github.com/losa201/Xorb/issues"
