apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.orchestrator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.orchestrator.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: orchestrator
    app.kubernetes.io/part-of: xorb
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.services.orchestrator.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.services.orchestrator.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/proxy-cpu-request: "100m"
        config.linkerd.io/proxy-memory-request: "128Mi"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        app.kubernetes.io/name: {{ .Values.services.orchestrator.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: orchestrator
        app.kubernetes.io/part-of: xorb
    spec:
      serviceAccountName: {{ .Values.services.orchestrator.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: orchestrator
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.global.imageRegistry }}{{ .Values.services.orchestrator.image.repository }}:{{ .Values.services.orchestrator.image.tag }}"
        imagePullPolicy: {{ .Values.services.orchestrator.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: XORB_ENVIRONMENT
          value: {{ .Values.global.xorb.environment }}
        - name: XORB_LOG_LEVEL
          value: {{ .Values.global.xorb.logLevel }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: xorb-database-secret
              key: database-url
        - name: TEMPORAL_HOST
          value: "{{ .Release.Name }}-temporal-frontend.{{ .Release.Namespace }}.svc.cluster.local:7233"
        - name: REDIS_URL
          value: "redis://{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local:6379"
        - name: QDRANT_URL
          value: "http://{{ .Release.Name }}-qdrant.{{ .Release.Namespace }}.svc.cluster.local:6333"
        - name: NEO4J_URI
          value: "bolt://{{ .Release.Name }}-neo4j.{{ .Release.Namespace }}.svc.cluster.local:7687"
        - name: NATS_URL
          value: "nats://{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222"
        - name: MAX_CONCURRENT_CAMPAIGNS
          value: "10"  # EPYC optimized
        - name: MAX_AGENTS_PER_CAMPAIGN
          value: "20"  # Higher for EPYC
        - name: ORCHESTRATOR_ELECTION_KEY
          value: "xorb-orchestrator-leader"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          {{- toYaml .Values.services.orchestrator.resources | nindent 10 }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: campaign-cache
          mountPath: /app/cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: campaign-cache
        emptyDir:
          sizeLimit: 1Gi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---