apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.api.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.api.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: xorb
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.services.api.service.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.services.api.service.type }}
  ports:
  - port: {{ .Values.services.api.service.port }}
    targetPort: {{ .Values.services.api.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ .Values.services.api.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.worker.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.worker.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: xorb
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: {{ .Values.services.worker.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.orchestrator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.orchestrator.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: orchestrator
    app.kubernetes.io/part-of: xorb
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ .Values.services.orchestrator.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---