apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: cyber-range-control
  labels:
    app: grafana
    component: monitoring
data:
  grafana.ini: |
    [server]
    protocol = http
    http_port = 3000
    domain = grafana.cyber-range.local
    enforce_domain = false
    root_url = http://grafana.cyber-range.local:3000/
    enable_gzip = true

    [database]
    type = sqlite3
    path = grafana.db

    [session]
    provider = file
    provider_config = sessions

    [security]
    admin_user = admin
    admin_password = SecureAdminPass123!
    secret_key = cyber_range_grafana_secret_key
    disable_gravatar = true
    allow_embedding = true

    [users]
    allow_sign_up = false
    allow_org_create = false
    auto_assign_org = true
    auto_assign_org_role = Viewer
    default_theme = dark

    [auth]
    disable_login_form = false
    disable_signout_menu = false

    [auth.anonymous]
    enabled = false

    [log]
    mode = console
    level = info

    [alerting]
    enabled = true
    execute_alerts = true

    [metrics]
    enabled = true
    interval_seconds = 10

    [feature_toggles]
    enable = publicDashboards

    [panels]
    disable_sanitize_html = false

  provisioning-datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        editable: true
        jsonData:
          httpMethod: POST
          prometheusType: Prometheus
          prometheusVersion: 2.45.0
          timeInterval: 15s

      - name: Elasticsearch
        type: elasticsearch
        access: proxy
        url: http://elasticsearch.cyber-range-blue:9200
        database: "[cyber-range-*]YYYY.MM.DD"
        interval: Daily
        timeField: "@timestamp"
        editable: true
        jsonData:
          esVersion: "8.8.0"
          timeInterval: 10s
          maxConcurrentShardRequests: 5
          logMessageField: message
          logLevelField: level

  provisioning-dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'cyber-range-dashboards'
        orgId: 1
        folder: 'Cyber Range'
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        allowUiUpdates: true
        options:
          path: /etc/grafana/provisioning/dashboards

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: cyber-range-control
  labels:
    app: grafana
    component: dashboards
data:
  cyber-range-overview.json: |
    {
      "dashboard": {
        "id": null,
        "title": "XORB Cyber Range Overview",
        "tags": ["cyber-range", "overview"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Exercise Status",
            "type": "stat",
            "targets": [
              {
                "expr": "cyber_range_mode",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "mappings": [
                  {
                    "options": {
                      "0": {
                        "text": "STAGING",
                        "color": "green"
                      },
                      "1": {
                        "text": "LIVE",
                        "color": "red"
                      },
                      "2": {
                        "text": "TERMINATED",
                        "color": "gray"
                      }
                    },
                    "type": "value"
                  }
                ]
              }
            },
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 0,
              "y": 0
            }
          },
          {
            "id": 2,
            "title": "Active Campaign",
            "type": "stat",
            "targets": [
              {
                "expr": "campaign_status",
                "refId": "A"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 6,
              "y": 0
            }
          },
          {
            "id": 3,
            "title": "Kill Switch Status",
            "type": "stat",
            "targets": [
              {
                "expr": "kill_switch_status",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "mappings": [
                  {
                    "options": {
                      "0": {
                        "text": "INACTIVE",
                        "color": "green"
                      },
                      "1": {
                        "text": "ACTIVE",
                        "color": "red"
                      }
                    },
                    "type": "value"
                  }
                ]
              }
            },
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 12,
              "y": 0
            }
          },
          {
            "id": 4,
            "title": "Team Performance",
            "type": "stat",
            "targets": [
              {
                "expr": "red_team_score",
                "refId": "A",
                "legendFormat": "Red Team"
              },
              {
                "expr": "blue_team_score",
                "refId": "B",
                "legendFormat": "Blue Team"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 18,
              "y": 0
            }
          },
          {
            "id": 5,
            "title": "Attack Activity",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(red_team_attack_attempts[5m])",
                "refId": "A",
                "legendFormat": "Attack Rate"
              },
              {
                "expr": "rate(blue_team_detections[5m])",
                "refId": "B",
                "legendFormat": "Detection Rate"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 8
            }
          },
          {
            "id": 6,
            "title": "Infrastructure Health",
            "type": "graph",
            "targets": [
              {
                "expr": "up{job=~\".*cyber-range.*\"}",
                "refId": "A",
                "legendFormat": "{{ job }} - {{ instance }}"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 8
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "15s"
      }
    }

  red-team-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Red Team Operations",
        "tags": ["cyber-range", "red-team"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Attack Success Rate",
            "type": "stat",
            "targets": [
              {
                "expr": "red_team_successful_attacks / red_team_attack_attempts",
                "refId": "A"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 0,
              "y": 0
            }
          },
          {
            "id": 2,
            "title": "Active Tools",
            "type": "stat",
            "targets": [
              {
                "expr": "count(up{job=\"red-team-infrastructure\", namespace=\"cyber-range-red\"} == 1)",
                "refId": "A"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 6,
              "y": 0
            }
          },
          {
            "id": 3,
            "title": "Targets Compromised",
            "type": "stat",
            "targets": [
              {
                "expr": "count(target_compromised == 1)",
                "refId": "A"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 12,
              "y": 0
            }
          },
          {
            "id": 4,
            "title": "Attack Timeline",
            "type": "graph",
            "targets": [
              {
                "expr": "red_team_attack_attempts",
                "refId": "A",
                "legendFormat": "Attack Attempts"
              },
              {
                "expr": "red_team_successful_attacks",
                "refId": "B",
                "legendFormat": "Successful Attacks"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 24,
              "x": 0,
              "y": 8
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "15s"
      }
    }

  blue-team-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Blue Team SOC",
        "tags": ["cyber-range", "blue-team"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Detection Rate",
            "type": "stat",
            "targets": [
              {
                "expr": "blue_team_detections / red_team_attack_attempts",
                "refId": "A"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 0,
              "y": 0
            }
          },
          {
            "id": 2,
            "title": "Alert Volume",
            "type": "stat",
            "targets": [
              {
                "expr": "rate(blue_team_alerts[1m])",
                "refId": "A"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 6,
              "y": 0
            }
          },
          {
            "id": 3,
            "title": "SIEM Health",
            "type": "stat",
            "targets": [
              {
                "expr": "up{job=\"elasticsearch\"}",
                "refId": "A"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 12,
              "y": 0
            }
          },
          {
            "id": 4,
            "title": "Incident Response Time",
            "type": "stat",
            "targets": [
              {
                "expr": "avg(blue_team_response_time)",
                "refId": "A"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 18,
              "y": 0
            }
          },
          {
            "id": 5,
            "title": "Security Events",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(security_events[5m])",
                "refId": "A",
                "legendFormat": "Security Events"
              },
              {
                "expr": "rate(false_positives[5m])",
                "refId": "B",
                "legendFormat": "False Positives"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 24,
              "x": 0,
              "y": 8
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "15s"
      }
    }

  network-security.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Network Security Monitoring",
        "tags": ["cyber-range", "network", "security"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Network Policy Violations",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(network_policy_violations[5m])",
                "refId": "A",
                "legendFormat": "Policy Violations"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 0
            }
          },
          {
            "id": 2,
            "title": "Blocked Connections",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(blocked_connections[5m])",
                "refId": "A",
                "legendFormat": "{{ source_namespace }} -> {{ dest_namespace }}"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 0
            }
          },
          {
            "id": 3,
            "title": "Traffic Flow Matrix",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(network_traffic_bytes[5m])",
                "refId": "A",
                "legendFormat": "{{ source }} -> {{ destination }}"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 24,
              "x": 0,
              "y": 8
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "15s"
      }
    }