apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: xorb-base
  
resources:
- deployment-api.yaml
- deployment-worker.yaml
- deployment-orchestrator.yaml
- services.yaml
- rbac.yaml
- configmaps.yaml
- secrets.yaml

commonLabels:
  app.kubernetes.io/part-of: xorb
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  xorb.ai/version: "2.0.0"
  
namePrefix: xorb-

namespace: xorb-system

images:
- name: xorb/api
  newTag: "2.0.0"
- name: xorb/worker  
  newTag: "2.0.0"
- name: xorb/orchestrator
  newTag: "2.0.0"