apiVersion: v1
kind: Service
metadata:
  name: xorb-api
  labels:
    app.kubernetes.io/name: xorb-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: xorb
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: xorb-api
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: xorb-worker
  labels:
    app.kubernetes.io/name: xorb-worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: xorb
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: xorb-worker
    app.kubernetes.io/component: worker
---
apiVersion: v1
kind: Service
metadata:
  name: xorb-orchestrator
  labels:
    app.kubernetes.io/name: xorb-orchestrator
    app.kubernetes.io/component: orchestrator
    app.kubernetes.io/part-of: xorb
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: xorb-orchestrator
    app.kubernetes.io/component: orchestrator