[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xorb-worker"
version = "2.0.0"
dependencies = [
    "temporalio>=1.0.0",
    # This installs the local package in editable mode
    "xorb-core @ {root:uri}/../../packages/xorb_core"
]
