apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "xorb-worker.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "xorb-worker.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          # Allow to xorb-api
          app.kubernetes.io/name: xorb-api
    ports:
    - protocol: TCP
      port: 8000
  - to:
    - podSelector:
        matchLabels:
          # Allow to pgvector
          app: postgresql
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          # Allow to neo4j
          app.kubernetes.io/name: neo4j
    ports:
    - protocol: TCP
      port: 7687
  - to:
    - podSelector:
        matchLabels:
          # Allow to temporal
          app.kubernetes.io/name: temporal
    ports:
    - protocol: TCP
      port: 7233
