apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xorb-worker.fullname" . }}-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  NEO4J_AUTH: {{ .Values.secrets.neo4jAuth | quote }}
