apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo_uid
          url: http://tempo:3200/tempo/traces/$${__value.raw}

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    editable: true
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: xorb
    user: xorb_user
    editable: true
    secureJsonData:
      password: xorb_secure_pass_2023
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400