apiVersion: apps/v1
kind: Deployment
metadata:
  name: xorb-api
  namespace: xorb-production
  labels:
    app: xorb-api
    tier: application
    component: api-gateway
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: xorb-api
  template:
    metadata:
      labels:
        app: xorb-api
        tier: application
        component: api-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      serviceAccountName: xorb-api
      containers:
      - name: xorb-api
        image: xorb/api:latest
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: secret
        - name: NVIDIA_API_KEY
          valueFrom:
            secretKeyRef:
              name: external-api-keys
              key: nvidia
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: external-api-keys
              key: openrouter
        - name: TEMPORAL_HOST
          value: "temporal:7233"
        - name: RATE_LIMIT_PER_MINUTE
          value: "100"
        - name: RATE_LIMIT_PER_HOUR
          value: "5000"
        - name: ENABLE_METRICS
          value: "true"
        - name: ENABLE_AUDIT_LOGGING
          value: "true"
        - name: CORS_ALLOW_ORIGINS
          value: "https://app.xorb-security.com,https://dashboard.xorb-security.com"
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: logs
          mountPath: /app/logs
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/readiness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        configMap:
          name: xorb-api-config
      - name: logs
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: xorb-api
  namespace: xorb-production
  labels:
    app: xorb-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: xorb-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xorb-api
  namespace: xorb-production
  labels:
    app: xorb-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: xorb-api-pdb
  namespace: xorb-production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: xorb-api
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: xorb-api-hpa
  namespace: xorb-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xorb-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
