apiVersion: v1
kind: Namespace
metadata:
  name: xorb-system
---
# Horizontal Pod Autoscaler for API service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: xorb-api-hpa
  namespace: xorb-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xorb-api
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Pods
    pods:
      metric:
        name: grpc_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
# HPA for embedding service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: xorb-embedding-hpa
  namespace: xorb-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xorb-embedding-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Pods
    pods:
      metric:
        name: embedding_requests_per_second
      target:
        type: AverageValue
        averageValue: "50"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 200
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
---
# HPA for worker service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: xorb-worker-hpa
  namespace: xorb-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xorb-worker
  minReplicas: 2
  maxReplicas: 12
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Object
    object:
      metric:
        name: temporal_workflow_task_queue_backlog
      target:
        type: Value
        value: "10"
      describedObject:
        apiVersion: v1
        kind: Service
        name: temporal-frontend
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 45
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 3
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 33
        periodSeconds: 120
---
# Vertical Pod Autoscaler for API service
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: xorb-api-vpa
  namespace: xorb-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xorb-api
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: xorb-api
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 4
        memory: 8Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
---
# VPA for embedding service
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: xorb-embedding-vpa
  namespace: xorb-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xorb-embedding-service
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: xorb-embedding-service
      minAllowed:
        cpu: 200m
        memory: 256Mi
      maxAllowed:
        cpu: 2
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
---
# VPA for worker service
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: xorb-worker-vpa
  namespace: xorb-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xorb-worker
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: xorb-worker
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 2
        memory: 3Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
---
# Pod Disruption Budgets for high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: xorb-api-pdb
  namespace: xorb-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: xorb-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: xorb-embedding-pdb
  namespace: xorb-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: xorb-embedding-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: xorb-worker-pdb
  namespace: xorb-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: xorb-worker