apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "xorb-api.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "xorb-api.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          # Allow from Traefik
          app.kubernetes.io/name: traefik
    ports:
    - protocol: TCP
      port: 8000
  - from:
    - podSelector:
        matchLabels:
          # Allow from Prometheus
          app.kubernetes.io/name: prometheus
    ports:
    - protocol: TCP
      port: 8000
  - from:
    - podSelector:
        matchLabels:
          # Allow from xorb-worker
          app.kubernetes.io/name: xorb-worker
  egress:
  - to:
    - podSelector:
        matchLabels:
          # Allow to pgvector
          app: postgresql
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          # Allow to neo4j
          app.kubernetes.io/name: neo4j
    ports:
    - protocol: TCP
      port: 7687
  - to:
    - podSelector:
        matchLabels:
          # Allow to temporal
          app.kubernetes.io/name: temporal
    ports:
    - protocol: TCP
      port: 7233
