apiVersion: v1
kind: ConfigMap
metadata:
  name: xorb-config
  namespace: xorb_platform
  labels:
    app: xorb_platform
    component: config
data:
  # API Configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"

  # Database Configuration
  DB_MIN_POOL_SIZE: "10"
  DB_MAX_POOL_SIZE: "50"
  DB_POOL_TIMEOUT: "30"
  DB_COMMAND_TIMEOUT: "60"
  DB_STATEMENT_CACHE_SIZE: "200"
  DB_ENABLE_PREPARED_STATEMENTS: "true"
  DB_POOL_RECYCLE: "3600"
  DB_POOL_PRE_PING: "true"

  # Redis Configuration
  REDIS_MAX_CONNECTIONS: "100"
  REDIS_RETRY_ON_TIMEOUT: "true"
  REDIS_HEALTH_CHECK_INTERVAL: "30"

  # PTaaS Configuration
  PTAAS_MAX_CONCURRENT_SCANS: "20"
  PTAAS_SCAN_TIMEOUT: "3600"
  PTAAS_RATE_LIMIT: "1000"
  PTAAS_ENABLE_STEALTH_MODE: "true"

  # Security Configuration
  RATE_LIMIT_PER_MINUTE: "1000"
  RATE_LIMIT_PER_HOUR: "50000"
  ENABLE_AUDIT_LOGGING: "true"
  ENABLE_SECURITY_HEADERS: "true"
  CORS_ALLOW_ORIGINS: "*"

  # Monitoring Configuration
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "true"
  METRICS_PORT: "9090"
  HEALTH_CHECK_INTERVAL: "30"

  # Intelligence Configuration
  ENABLE_BEHAVIORAL_ANALYTICS: "true"
  ENABLE_THREAT_HUNTING: "true"
  ENABLE_FORENSICS: "true"
  ML_MODEL_REFRESH_INTERVAL: "3600"

  # Compliance Configuration
  COMPLIANCE_FRAMEWORKS: "PCI-DSS,HIPAA,SOX,ISO-27001,GDPR,NIST"
  COMPLIANCE_SCAN_INTERVAL: "86400"
  COMPLIANCE_REPORT_RETENTION: "2592000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: xorb-monitoring
  labels:
    app: prometheus
    component: config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: 'xorb-production'
        environment: 'production'

    rule_files:
      - "/etc/prometheus/rules/*.yml"

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093

    scrape_configs:
      - job_name: 'xorb-api'
        static_configs:
          - targets: ['xorb-api:9090']
        metrics_path: /metrics
        scrape_interval: 30s
        scrape_timeout: 10s

      - job_name: 'xorb-orchestrator'
        static_configs:
          - targets: ['xorb-orchestrator:9091']
        metrics_path: /metrics
        scrape_interval: 30s

      - job_name: 'ptaas-scanner'
        static_configs:
          - targets: ['ptaas-scanner:9092']
        metrics_path: /metrics
        scrape_interval: 60s

      - job_name: 'postgres-exporter'
        static_configs:
          - targets: ['postgres-exporter:9187']
        scrape_interval: 30s

      - job_name: 'redis-exporter'
        static_configs:
          - targets: ['redis-exporter:9121']
        scrape_interval: 30s

      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):10250'
            target_label: __address__
            replacement: '${1}:9100'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: xorb-monitoring
  labels:
    app: grafana
    component: dashboards
data:
  xorb-overview.json: |
    {
      "dashboard": {
        "id": null,
        "title": "XORB Platform Overview",
        "description": "Comprehensive overview of XORB platform metrics",
        "tags": ["xorb", "security", "ptaas"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "API Request Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(http_requests_total[5m])",
                "legendFormat": "{{method}} {{handler}}"
              }
            ]
          },
          {
            "id": 2,
            "title": "Active Security Scans",
            "type": "stat",
            "targets": [
              {
                "expr": "ptaas_active_scans_total",
                "legendFormat": "Active Scans"
              }
            ]
          },
          {
            "id": 3,
            "title": "Vulnerability Detection Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(ptaas_vulnerabilities_detected_total[1h])",
                "legendFormat": "{{severity}}"
              }
            ]
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s"
      }
    }
