name: Repository Sanitation

on:
  push:
    branches: [ main, adr-hardening-security-lockdown ]
  pull_request:
    branches: [ main, adr-hardening-security-lockdown ]

jobs:
  repo-sanitation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Repository Doctor
        id: repo_doctor
        run: |
          python tools/repo_doctor.py

      - name: Check for duplicates
        id: check_duplicates
        run: |
          if [ -s "tools/repo_audit/duplicates.csv" ] && [ $(wc -l < "tools/repo_audit/duplicates.csv") -gt 1 ]; then
            echo "Duplicate files detected:"
            cat tools/repo_audit/duplicates.csv
            echo "duplicates_found=true" >> $GITHUB_OUTPUT
          else
            echo "duplicates_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for Redis pubsub usage (ADR-002 guard)
        id: check_redis
        run: |
          if [ -s "tools/repo_audit/redis_pubsub_usage.txt" ]; then
            echo "Redis pubsub usage detected (ADR-002 violation):"
            cat tools/repo_audit/redis_pubsub_usage.txt
            echo "redis_violation=true" >> $GITHUB_OUTPUT
          else
            echo "redis_violation=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload audit reports
        uses: actions/upload-artifact@v3
        with:
          name: repo-audit-reports
          path: tools/repo_audit/

      - name: Fail if duplicates found
        if: steps.check_duplicates.outputs.duplicates_found == 'true'
        run: |
          echo "ERROR: Duplicate files detected. Please remove duplicates before merging."
          exit 1

      - name: Fail if Redis pubsub usage found (ADR-002 violation)
        if: steps.check_redis.outputs.redis_violation == 'true'
        run: |
          echo "ERROR: Redis pubsub/subscribe usage detected. This violates ADR-002."
          echo "Please use the approved messaging patterns instead."
          exit 1
