name: security-push-protection

on: [push, pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: detect --source . --no-banner --redact --config .gitleaks.toml
  adr-002-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Forbid Redis bus usage
        run: |
          set -euo pipefail
          ! grep -RInE '\b(redis\.(pubsub|subscribe|psubscribe)|redis\.client\.PubSub)\b' -- . || { echo "Redis bus usage detected"; exit 1; }
